title = "Susan Qi"
baseURL = "https://regal-manatee-7cba95.netlify.app"

languageCode = "en-us"
theme = "ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true







[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = "https://www.linkedin.com/in/shichen-susan-qi-2654b7170/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "img/cornell.jpeg"
  recent_posts_number = 2



[menu]

  [[menu.main]]
    identifier = 'posts'
    name = "Posts"
    url = '/posts/'
    weight = 1


  [[menu.main]]
    name = "Resume"
    url = "/doc/qi.shichen.pdf/"
    weight = 2.5


  [[menu.main]]
    identifier = 'contact'
    name = "Contact"
    url = '/contact/contact/'
    weight = 1




